development:
  secret_key_base: 7b3e573dd3a59b8a1596c01b98d080f682b7df82bad704441ec1edf4202d8cbeaea76939b42e26e83a1f6d15ebd82079f28aee51e6b54dca2dc5b9c899fcf4d8
  connect:
    key: ""
  starter_pack:
    zuora_login: blah
    zuora_password: blah
    zuora_url: https://apisandbox.zuora.com/apps/services/a/68.0
